server:
  port: 0  # 使用随机端口

spring:
  application:
    name: multi-protocol-gateway-engine

logging:
  level:
    com.whosly.gateway: INFO
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

gateway:
  # 数据库类型配置
  proxy-db-type: mysql
  # 代理端口
  proxy-port: 3307

  # 目标数据库配置
  target:
    host: localhost
    port: 13308
    username: root
    password: Aa123456.
    database: demo

  connection:
    pool:
      initial-size: 5
      max-size: 20
      min-idle: 2
  security:
    authentication:
      enabled: true